services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    privileged: true
    user: root
    networks:
      - monitoring-net
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    networks:
      - monitoring-net
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - monitoring-net
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    networks:
      - monitoring-net
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  monitoring-net:

volumes:
  jenkins_data:
  sonarqube_data:
  grafana_data:
